### ISSUE TITLE
which version of JSC is based?

### ISSUE THREAD

**Issue by hurims** [openaphid/AJ#1]
Hi, I'm interested in your project.
I'm trying to figure out which part of JSC you've improved by comparing source ocdes of JavaScriptCore of Webkit and your AJ project.

Can I know which version of JSC is your AJ project's baseline?

**Comment by openaphid** [comment]
It's based on a version for iOS4.3. Technically, I didn't add any optimization into it, I only modified it to meet my requirements for OpenAphid-Engine
